### PR TITLE
Fix syntax highlighting in README

### PR DESCRIPTION
**Pull request by nicoddemus**
For some reason GH does not recognize `.. code-block: python3`, but `.. code-block: python` works even for Python 3 syntax.

### CODE REVIEW

**Comment by njsmith** [comment]
Ugh. You're not wrong, but I bet this will break syntax highlighting on pypi, because pygments definitely treats `python` and `python3` differently. Probably we should at least file bugs on GitHub and pygments asking them to fix there things.

**Comment by nicoddemus** [comment]
Thanks, sorry I forgot to get back at this myself. 👍

**Comment by njsmith** [comment]
Github just added `python3` as an alias for `python` in the library they use for syntax highlighting: https://github.com/github/linguist/pull/4026

I'm not sure how long this will take to flow from "committed to the open source library" to "deployed on the production site" – possibly a few weeks.

**Comment by njsmith** [comment]
But in any case I guess I'll close this, since the current solution works with pypi/sphinx and the github rendering will fix itself eventually, and in the mean time it's not *too* terrible. Thanks for bringing this up though :-)

**Comment by nicoddemus** [comment]
Sure thing, thanks for the update!

**Pull request closed without merging**
